export const initialState = {
    user: null,
    allUsers: null,
    allSongs: null,
    allArtists: null,
    allPlaylists: null,
    allAlbums: null,
    filterTerm: "all",
    artistFilter: null,
    languageFilter: null,
    albumFilter: null,
    userPlaylists: null,
    currentPlaylist: null,
    alertType: null,
    isSongPlaying: false,
    songIndex: "",
    miniPlayer: false,
};